### ISSUE TITLE
Update data sources link for Feature Data Source CSV

### ISSUE THREAD

**Issue by kohearn-cwf** [Canadian-Wildlife-Federation/CABD#40]
I'd like to update the following line to reference https://cabd-docs.netlify.app/docs_user/docs_user_data_sources.html instead of https://aquaticbarriers.ca/data-sources. @egouge is there anything additional that needs to be done to reflect this change in the app / CSV download? Should I redeploy the app afterwards?

https://github.com/Canadian-Wildlife-Federation/CABD/blob/216ebc2cf7fa874d8b862cac831a64a6ee0bda28/cabd-web/src/main/java/org/refractions/cabd/serializers/FeatureDataSourceListCsvSerializer.java#L88

**Comment by egouge** [comment]
Just updating this line should be fine, I don't believe anything else needs to be modified. When you commit the changes to github it should automatically start the redeployment process so you shouldn't need to do anything other than wait (you can see the process running on the Action page).
