### ISSUE TITLE
Remove <attribute>_dsfid fields from <featuretype>_attribute_source tables

### ISSUE THREAD

**Issue by egouge** [Canadian-Wildlife-Federation/CABD#46]
These columns were added as a part of the initial feature source tracking but as of 03152022 updates they are no longer used. The datasource to featureid link is stored in the <featuretype>_feature_source table instead. We didn't remove these at the time but they should be removed eventually to prevent duplication and confusion.

See the end of cabd/cabd.updates.03152022.datasources.sql script for examples.

**Comment by kohearn-cwf** [comment]
I can take care of this today before the DB migration - any concerns with that?

**Comment by egouge** [comment]
No concerns on my side. There is no rush to get it done either so if it makes sense for you to wait that's fine - I just didn't want it forgotten about.

**Comment by kohearn-cwf** [comment]
Ok! This is all finished up - it's actually a great time to do this as we are working through some tasks from the backlog before the migration.
