### ISSUE TITLE
Update the updates_pending view once feature staging tables are created 

### ISSUE THREAD

**Issue by egouge** [Canadian-Wildlife-Federation/CABD#53]
This view supports the pending_update field in the features API - we need to configure it such that is returns the cabd_ids for every feature that has a review pending.

create view cabd.updates_pending as 
select null::uuid as cabd_id;

**Comment by kohearn-cwf** [comment]
Hi Emily, the staging tables are now available in the database as part of [cabd-database/cabd/cabd.updates.12082022.sql](https://github.com/Canadian-Wildlife-Federation/CABD/blob/main/cabd-database/cabd/cabd.updates.12082022.sql).

Please let me know if you need anything else!

**Comment by egouge** [comment]
Hi Katherine,
Is the plan to remove rows from these tables after the updates are integrated into the core feature tables OR are you just changing the status to 'done' and leaving the features in this table? I want to use these tables to determine what features have updates pending and I can either just select all features from the tables or select all features where status != 'done'.

**Comment by kohearn-cwf** [comment]
The plan is to remove rows from these tables after the updates are integrated into the core feature tables - we will mark the rows as 'done' and then delete them right after by filtering for the rows with a a status of 'done'.

**Comment by egouge** [comment]
Thanks. I've updated that file to include the sql to recreate the view. I didn't see the tables in the database yet, so when you run the script in the db, also run the view sql and this issue should be resolved.

**Comment by kohearn-cwf** [comment]
The tables should be available in the DB in the cabd schema - do you see the cabd.dam_updates, cabd.fishway_updates, and cabd.waterfall_updates tables in that schema? If not I can check permissions. They are owned by the cabd role right now.

**Comment by egouge** [comment]
sorry - you're right. They are there, I had to refresh the viewer I was using (and fix a typo).  The view is created now, so I'll close off this ticket.
